exclude: '^docs/conf.py'

repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: flake8
    args: ['--max-line-length=88']  # default of Black

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.720
  hooks:
    - id: mypy
      exclude: ^(docs/|example-plugin/|tests/fixtures)
